#----------------------------------------------------------
# Makefile for Final Project: Forks                       |
# Written by: Anthony Perez                               |
# To use type 'make' into the command line                |
#----------------------------------------------------------
# Set Compiler to use gcc
#----------------------------------------------------------
CC = gcc

# Files to be compiled, process.h and convert.h must be present in main dir.
# ---------------------------------------------------------
FILES1 = forker.c

# Executable file output name
# ---------------------------------------------------------
OUT_EXE1 = forker.out

# Build program
# ---------------------------------------------------------
build: $(FILES1) $(FILES2)
		$(CC) -o $(OUT_EXE1) $(FILES1)

#End of MakeFile ------------------------------------------
